<?php

namespace DoctrineProxies\__CG__\PortlandLabs\Concrete5\MigrationTool\Entity\ContentMapper;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UnmappedTargetItem extends \PortlandLabs\Concrete5\MigrationTool\Entity\ContentMapper\UnmappedTargetItem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'source_item_identifier', 'item_id', 'item_type', 'item_name'];
        }

        return ['__isInitialized__', 'id', 'source_item_identifier', 'item_id', 'item_type', 'item_name'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UnmappedTargetItem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function isMapped()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isMapped', []);

        return parent::isMapped();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getItemId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemId', []);

        return parent::getItemId();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemId($item_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemId', [$item_id]);

        return parent::setItemId($item_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemType', []);

        return parent::getItemType();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemType($item_type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemType', [$item_type]);

        return parent::setItemType($item_type);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemName', []);

        return parent::getItemName();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemName($item_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemName', [$item_name]);

        return parent::setItemName($item_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getSourceItemIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSourceItemIdentifier', []);

        return parent::getSourceItemIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function setSourceItemIdentifier($source_item_identifier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSourceItemIdentifier', [$source_item_identifier]);

        return parent::setSourceItemIdentifier($source_item_identifier);
    }

    /**
     * {@inheritDoc}
     */
    public function matches(\PortlandLabs\Concrete5\MigrationTool\Entity\ContentMapper\TargetItemInterface $targetItem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'matches', [$targetItem]);

        return parent::matches($targetItem);
    }

}
