<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-09-02T20:32:21+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'UTC',
];
