<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-09-11T18:05:21+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.5',
    'version_db_installed' => '20201116182100',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1630614741,
        'do_page_reindex_check' => false,
        'latest_version' => '8.5.5',
    ],
];
