<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-09-09T14:32:47+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.misc.browser_toolbar_color
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'God of Insects',
            'misc' => [
                'favicon_fid' => 942,
                'iphone_home_screen_thumbnail_fid' => null,
                'modern_tile_thumbnail_fid' => null,
                'modern_tile_thumbnail_bgcolor' => null,
                'browser_toolbar_color' => null,
            ],
        ],
    ],
];
